# Generated by Django 6.0.2 on 2026-03-02 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(verbose_name=django.core.validators.MinLengthValidator(256)),
        ),
    ]
